### ISSUE TITLE
How to disable non Vega cards from xrig.exe

### ISSUE THREAD

**Issue by stasxpulse** [arnesson/xrig#1]
Hi,
I have a mix video's in RIG, is it possible to select only specific GPU for this miner?
Thanks

**Comment by robertarnesson** [comment]
Hi yes you can configure the threads individually:

"threads": [
        {"index": 0, "intensity": 1932, "worksize": 8, "affine_to_cpu": false},
        {"index": 0, "intensity": 1932, "worksize": 8, "affine_to_cpu": false}
],

**Comment by stasxpulse** [comment]
Thank you, works like a charm on 64 and FE.

**Comment by robertarnesson** [comment]
let me know if you have any issues, crashes or instability

**Comment by stasxpulse** [comment]
Robert,

Somehow hashrate going down from 8100K (3 Vega64 + 1 Vega FE) to 7.3-7.6K, in about 1 hour.
Can you tell me if you have webserver built-in like xmr-aeon-stack.
In this case I can run PowerShell script to restart miner if hashrate drops more than 300-400 H/s.

Thanks.

**Comment by robertarnesson** [comment]
you have the api port configured so you can monitor the api at localhost:4444 and restart if there is a drop. Also note that right now the same profile will be applied to all cards. Perhaps I will have to add the possibility to specify a profile per card

**Comment by stasxpulse** [comment]
Yes, I used same profile for 64 and FE from OverDriveNT.

Ok. Thanks

**Comment by stasxpulse** [comment]
Just for clarification:
[2018-03-05 16:05:09] new job from cryptonight.eu.nicehash.com:3355 diff 200007 <----
[2018-03-05 16:05:09] use pool xmr-us-east1.nanopool.org:14444 142.44.243.6
[2018-03-05 16:05:18] new job from cryptonight.eu.nicehash.com:3355 diff 200007 <------
[2018-03-05 16:05:26] speed 10s/60s/15m 8460.5 n/a n/a H/s max: 8456.1 H/s
[2018-03-05 16:05:27] new job from cryptonight.eu.nicehash.com:3355 diff 200007 <------
[2018-03-05 16:05:27] rejected (0/1) diff 200007 "Job not found." (115 ms)
[2018-03-05 16:05:36] GPU 0 10s/60s/15m 393.6 n/a n/a H/s
[2018-03-05 16:05:36] GPU 1 10s/60s/15m 984.5 n/a n/a H/s
[2018-03-05 16:05:36] GPU 1 10s/60s/15m 995.0 n/a n/a H/s
[2018-03-05 16:05:36] GPU 2 10s/60s/15m 1009.1 n/a n/a H/s
[2018-03-05 16:05:36] GPU 2 10s/60s/15m 1018.3 n/a n/a H/s
[2018-03-05 16:05:36] GPU 3 10s/60s/15m 997.9 n/a n/a H/s
[2018-03-05 16:05:36] GPU 3 10s/60s/15m 1008.8 n/a n/a H/s
[2018-03-05 16:05:36] GPU 4 10s/60s/15m 1019.3 n/a n/a H/s
[2018-03-05 16:05:36] GPU 4 10s/60s/15m 1011.0 n/a n/a H/s
[2018-03-05 16:05:36] speed 10s/60s/15m 8437.4 n/a n/a H/s max: 8456.1 H/s
[2018-03-05 16:05:39] GPU 0 10s/60s/15m 393.5 n/a n/a H/s
[2018-03-05 16:05:39] GPU 1 10s/60s/15m 985.3 n/a n/a H/s
[2018-03-05 16:05:39] GPU 1 10s/60s/15m 993.1 n/a n/a H/s
[2018-03-05 16:05:39] GPU 2 10s/60s/15m 1010.2 n/a n/a H/s
[2018-03-05 16:05:39] GPU 2 10s/60s/15m 1018.3 n/a n/a H/s
[2018-03-05 16:05:39] GPU 3 10s/60s/15m 989.4 n/a n/a H/s
[2018-03-05 16:05:39] GPU 3 10s/60s/15m 990.7 n/a n/a H/s
[2018-03-05 16:05:39] GPU 4 10s/60s/15m 1019.0 n/a n/a H/s
[2018-03-05 16:05:39] GPU 4 10s/60s/15m 1011.4 n/a n/a H/s
[2018-03-05 16:05:39] speed 10s/60s/15m 8410.9 n/a n/a H/s max: 8456.1 H/s

**Comment by robertarnesson** [comment]
correct, it starts with the dev fee. I will update the README to reflect this

**Comment by stasxpulse** [comment]
Just an example on hash rate drop... Again, this is probably my local issue....

speed 10s/60s/15m 7790.0 7765.9 n/a H/s **max: 8456.1 H/s**

**Comment by robertarnesson** [comment]
do you have this problem with other miners as well?

**Comment by stasxpulse** [comment]
From time to time, but not in 15 minutes after initial run.
Over last week I used xmr-aeon-stack, and I saw restarts for miner probably about 1-2 a day, but my config for PS script was configured to restart miner if hash rate drops more than 250 H/s.

**Comment by robertarnesson** [comment]
any specific card that is dropping?

**Comment by stasxpulse** [comment]
Yes, looks like Vega FE - looks like, at least on 2nd attempt to run... sort of restart if hash rate lowered...

**Comment by robertarnesson** [comment]
I dont have any FE cards, just 56's, but I will do some benchmarking on my side if I can find anything that causes drops

**Comment by stasxpulse** [comment]
Ok. Thank you. I will check if I can find anything on my rig what cause this issue.

**Comment by robertarnesson** [comment]
I cant get my cards to drop. they are always within 40-40 H/s from the max value. I'm running all cards at around 1900 H/s.

One thing you can try is to run P6 and P7 at the same frequency.

[
            {"clock": 852,  "vddc": 0.800},
            {"clock": 991,  "vddc": 0.900},
            {"clock": 1084, "vddc": 0.900},
            {"clock": 1138, "vddc": 0.900},
            {"clock": 1150, "vddc": 0.900},
            {"clock": 1202, "vddc": 0.900},
            {"clock": 1408, "vddc": 0.900},
            {"clock": 1408, "vddc": 0.900}
]

this way the card wont roll back on its own

**Comment by stasxpulse** [comment]
Thank you, Will try again... Still not have much time to edit JJ Hashrate PowerShell script to get information your your JSON output.

**Comment by stasxpulse** [comment]
Robert,
Please comparison between this and xmr-aeon-stack miners;

Same environment, same session, same GPU and settings:

GPO0 - 7950
GPU 1.2 -Vega 64
GPU 3 -Vega FE
GPU 4 - Vega 64

xrig:
2018-03-09 10:37:19] GPU 0 10s/60s/15m 392.2 392.1 n/a H/s
[2018-03-09 10:37:19] GPU 1 10s/60s/15m 634.6 634.8 n/a H/s
[2018-03-09 10:37:19] GPU 1 10s/60s/15m 698.1 698.2 n/a H/s
[2018-03-09 10:37:19] GPU 2 10s/60s/15m 633.7 633.6 n/a H/s
[2018-03-09 10:37:19] GPU 2 10s/60s/15m 699.4 699.4 n/a H/s
[2018-03-09 10:37:19] GPU 3 10s/60s/15m 609.5 594.6 n/a H/s
[2018-03-09 10:37:19] GPU 3 10s/60s/15m 608.9 596.0 n/a H/s
[2018-03-09 10:37:19] GPU 4 10s/60s/15m 634.1 634.6 n/a H/s
[2018-03-09 10:37:19] GPU 4 10s/60s/15m 698.9 698.3 n/a H/s
[2018-03-09 10:37:19] speed 10s/60s/15m 5609.4 5581.6 n/a H/s max: 5607.0 H/s

[2018-03-09 10:37:22] GPU 0 10s/60s/15m 392.2 392.1 n/a H/s
[2018-03-09 10:37:22] GPU 1 10s/60s/15m 634.5 634.7 n/a H/s
[2018-03-09 10:37:22] GPU 1 10s/60s/15m 698.9 698.2 n/a H/s
[2018-03-09 10:37:22] GPU 2 10s/60s/15m 633.4 633.6 n/a H/s
[2018-03-09 10:37:22] GPU 2 10s/60s/15m 698.9 699.4 n/a H/s
[2018-03-09 10:37:22] GPU 3 10s/60s/15m 600.4 595.0 n/a H/s
[2018-03-09 10:37:22] GPU 3 10s/60s/15m 604.3 596.7 n/a H/s
[2018-03-09 10:37:22] GPU 4 10s/60s/15m 634.3 634.6 n/a H/s
[2018-03-09 10:37:22] GPU 4 10s/60s/15m 697.2 698.3 n/a H/s
[2018-03-09 10:37:22] speed 10s/60s/15m 5594.1 5582.6 n/a H/s max: 5607.0 H/s

XMR-aeon-stack:
-----------------------------------------------------------------
HASHRATE REPORT - AMD
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 |  406.1 |  406.3 |   (na) |  1 |  965.6 |  962.4 |   (na) |
|  2 | 1059.8 | 1060.2 |   (na) |  3 |  961.9 |  960.7 |   (na) |
|  4 | 1057.9 | 1058.6 |   (na) |  5 | 1012.6 | 1013.2 |   (na) |
|  6 | 1010.0 | 1008.7 |   (na) |  7 |  958.1 |  961.3 |   (na) |
|  8 | 1053.8 | 1057.3 |   (na) |
Totals (AMD):  8485.9 8488.6    0.0 H/s

Not sure why hashrate have big difference now.

OverDriveNT for xmr-aeon-stack:
[Profile_0]
Name=vega_64
GPU_P0=852;800
GPU_P1=991;900
GPU_P2=1084;900
GPU_P3=1138;900
GPU_P4=1150;900
GPU_P5=1202;900
GPU_P6=1400;900
GPU_P7=1408;900
Mem_P0=167;900
Mem_P1=500;900
Mem_P2=800;900
Mem_P3=1100;900
Fan_Min=3500
Fan_Max=4900
Fan_Target=65
Fan_Acoustic=4900
Power_Temp=70
Power_Target=0

[Profile_1]
Name=vega_fe
GPU_P0=852;800
GPU_P1=991;900
GPU_P2=1084;900
GPU_P3=1138;900
GPU_P4=1150;900
GPU_P5=1202;900
GPU_P6=1400;900
GPU_P7=1408;925
Mem_P0=167;900
Mem_P1=500;900
Mem_P2=800;900
Mem_P3=1100;900
Fan_Min=3500
Fan_Max=4900
Fan_Target=60
Fan_Acoustic=0
Power_Temp=75
Power_Target=0

config.json in xrig:
			{"clock": 852, "vddc": 0.800},
			{"clock": 991, "vddc": 0.900},
			{"clock": 1084, "vddc": 0.900},
			{"clock": 1138, "vddc": 0.900},
			{"clock": 1150, "vddc": 0.900},
			{"clock": 1202, "vddc": 0.900},
			{"clock": 1408, "vddc": 0.900},
			{"clock": 1408, "vddc": 0.900}
        ],
        "memory": [
            {"clock": 167, "vddc": 0.800},
            {"clock": 500, "vddc": 0.800},
            {"clock": 800, "vddc": 0.900},
            {"clock": 1100, "vddc": 0.910}

Thanks.

**Comment by stasxpulse** [comment]
I think issue with memory clock, for some reason I see memory clock is only 500Mhz insted 1100

**Comment by stasxpulse** [comment]
JSON output per card:

VEGA 64
{
            "bus_id": 12,
            "adapter_index": 21,
            "device_name": "Radeon RX Vega",
            "temperature": 32,
            "core_clock": 1408,
            "memory_clock": 800,
            "fan_speed": 3003,
            "profile": {
                "system": [
                    {
                        "clock": 852,
                        "vddc": 0.875
                    },
                    {
                        "clock": 991,
                        "vddc": 0.9
                    },
                    {
                        "clock": 1098,
                        "vddc": 0.913
                    },
                    {
                        "clock": 1171,
                        "vddc": 0.925
                    },
                    {
                        "clock": 1191,
                        "vddc": 0.938
                    },
                    {
                        "clock": 1270,
                        "vddc": 0.95
                    },
                    {
                        "clock": 1408,
                        "vddc": 0.91
                    },
                    {
                        "clock": 1408,
                        "vddc": 0.91
                    }
                ],
                "memory": [
                    {
                        "clock": 167,
                        "vddc": 0.875
                    },
                    {
                        "clock": 500,
                        "vddc": 0.875
                    },
                    {
                        "clock": 800,
                        "vddc": 0.913
                    },
                    {
                        "clock": 1100,
                        "vddc": 0.92
                    }
                ],
                "target_temperature": 75
            },
            "threads": [
                {
                    "intensity": 1830,
                    "hashrate_10s": 812.49,
                    "hashrate_60s": 0.0,
                    "hashrate_15m": 0.0
                },
                {
                    "intensity": 2016,
                    "hashrate_10s": 890.06,
                    "hashrate_60s": 0.0,
                    "hashrate_15m": 0.0
                }
            ],
            "hashrate_10s": 1702.55,
            "hashrate_60s": 0.0,
            "hashrate_15m": 0.0
        },

VEGA FE:

{
            "bus_id": 16,
            "adapter_index": 17,
            "device_name": "Radeon Vega Frontier Edition",
            "temperature": 64,
            "core_clock": 1408,
            "memory_clock": 500,
            "fan_speed": 1286,
            "profile": {
                "system": [
                    {
                        "clock": 852,
                        "vddc": 0.8
                    },
                    {
                        "clock": 991,
                        "vddc": 0.9
                    },
                    {
                        "clock": 1084,
                        "vddc": 0.9
                    },
                    {
                        "clock": 1138,
                        "vddc": 0.9
                    },
                    {
                        "clock": 1150,
                        "vddc": 0.9
                    },
                    {
                        "clock": 1202,
                        "vddc": 0.9
                    },
                    {
                        "clock": 1408,
                        "vddc": 0.91
                    },
                    {
                        "clock": 1408,
                        "vddc": 0.91
                    }
                ],
                "memory": [
                    {
                        "clock": 1100,
                        "vddc": 0.92
                    }
                ],
                "target_temperature": 75
            },
            "threads": [
                {
                    "intensity": 2016,
                    "hashrate_10s": 592.85,
                    "hashrate_60s": 0.0,
                    "hashrate_15m": 0.0
                },
                {
                    "intensity": 2016,
                    "hashrate_10s": 558.68,
                    "hashrate_60s": 0.0,
                    "hashrate_15m": 0.0
                }
            ],
            "hashrate_10s": 1151.53,
            "hashrate_60s": 0.0,
            "hashrate_15m": 0.0
        }
    ],
    "results": {
        "diff_current": 200007,
        "shares_good": 0,
        "shares_total": 0,
        "avg_time": 0,
        "hashes_total": 0,
        "best": [
