### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by sshimko** [arnesson/xrig#2]
It does indeed build on Linux, however the ADL shared object is never loaded so anything after ADL::ADL will segfault. Additionally, the cross-platform logic to load symbols on both platforms is missing.

The branch below *should* build and work on both Windows and Linux, but I don't use Windows so I can't eb sure ;) I won't submit a formal PR since "real" support would entail fleshing out the common parts and identifying any other symbols tat needs to be addressed on Linux, but if you're interested this, plus the shared object, gets things going:
https://github.com/sshimko/xrig/tree/linux-adl

Based on the symbol names I'm guessing there won't be feature parity between the two platforms such as the ability to set VDDC and clocks.

I hacked this together so I could do a quick benchmark. xmr-stak gets about 50h/s more with the same parameters on a Vega 56 on Ubuntu 16.04 with the 17.50 AMD Pro/ROCM drivers and libs.

**Comment by robertarnesson** [comment]
Thats great, I will take a look at this!

**Comment by sshimko** [comment]
One Red Devil Vega 56 on Cryptonight, mining for hours on each run:

miner | 10s | 60s | 15m | max |
------ | ------- | ------- | ------ | ------- 
xmr-stak | 1144.9 | 1142.0 | 1142.0 | 1346.8
xrig | 1120.0 | 1103.1 | 1088.2 | 1157.5


Pitiful compared to Windows.

**Comment by robertarnesson** [comment]
Very strange.. there should not be any performance difference. CPU mining is off in xmr-stak?

**Comment by sshimko** [comment]
It is run with --noCPU and --noNVIDIA.  The GPU_* environment variables are also the same.
