### ISSUE TITLE
Ram Temp Target or min fan speed

### ISSUE THREAD

**Issue by hbiyik** [arnesson/xrig#3]
One of the issues with mining vega is HBM2 gets hotter than the actualy core especially mining cn, but driver controls the fans according to the core temp. So setting target temp is cooking hbm2 rams by time in mid/long term.

for this particular reason, generally a min speed of 3000 is set to keep rams cool.

So will there be fan control according to hbm2 temp? or to work around is there any min speed feature for fans?

**Comment by robertarnesson** [comment]
shouldnt just setting a lower target temp have the same effect? regardless, its not difficult to add an option for min speed

**Comment by hbiyik** [comment]
not always, rams may not keep calm as fast as gpu, even if you set low target temp, overtime when the target reaches, and fans get slow, cpu can keeps cool but hbm keeps adding on it over and over (because cn uses more than it uses gpu). it is very common to apply min fan speed, thats why overdrivntool has it.

**Comment by robertarnesson** [comment]
I added the option min_fan_limit, see 2564787f7fd7f15d48a7769b315217ec7adc6953

you can try it now by building from master yourself

**Comment by hbiyik** [comment]
tested and works as expected, thanks for your time.
